name: internship_assignment
description: A new Flutter project for internship assignment.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lucide_icons: ^0.257.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  hive_ce_generator: ^1.9.2
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
